name: kgbot_dev
channels:
  - defaults
dependencies:
  - python==3.12.2
  - pip==23.3.1
  - setuptools==68.2.2
  - xz==5.4.6
  - bzip2==1.0.8
  - wheel==0.41.2
  - pip:
      - faiss-cpu==1.8.0
      - ipykernel==6.29.3
      - langchain==0.1.11
      - langchain_community==0.0.27
      - langchain_core==0.1.30
      - langchain_openai==0.0.8
      - langgraph==0.0.26
      - langsmith==0.1.22
      - matplotlib==3.8.3
      - networkx==3.2.1
      - pandas==2.2.1
      - python-dotenv==1.0.1
      - rdflib==7.0.0
      - Requests==2.31.0
      - seaborn==0.13.2
      - SPARQLWrapper==2.0.0
      - SPARQLWrapper==2.0.0
      - tiktoken==0.5.2
      - tqdm==4.66.1
      - VizKG==1.0.9


