name: kgbot
channels:
  - conda-forge
  - pytorch-nightly
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.11.6
  - bzip2==1.0.8
  - setuptools=68.2.2
  - wheel=0.41.2
  - xz==5.4.6
  - pip:
      - app==0.0.1
      - "codeboxapi>=0.0.19,<0.2.0"
      - chromadb==0.4.24
      - codeinterpreterapi==0.0.14
      - faiss-cpu==1.8.0
      - ipykernel==6.29.3
      - jupyter-kernel-gateway==3.0.1
      - kaleido==0.2.1
      - langchain==0.1.11
      - langchainhub==0.1.15
      - langchain_community==0.0.27
      - langchain_core==0.1.30
      - langchain_openai==0.0.8
      - langgraph==0.0.26
      - langsmith==0.1.22
      - matplotlib==3.8.3
      - networkx==3.2.1
      - openai==1.44.0
      - pandas==2.2.1
      - plotly==5.20.0
      - psycopg2-binary
      - pydantic==2.7.0
      - python-dotenv==1.0.1
      - rdflib==7.0.0
      - Requests==2.31.0
      - seaborn==0.13.2
      - SPARQLWrapper==2.0.0
      - SQLAlchemy==2.0.22
      - tiktoken==0.5.2
      - tqdm==4.66.1
      - numpy==1.26.0
      - httpx==0.27.2
      - scikit-learn==1.5.1
