name: Deploy Documentation
on:
  workflow_dispatch:  
    inputs:
      branch:
        description: "Branch to run action on"
        required: false
        default: "main"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs \
                      mkdocs-material \
                      mkdocstrings \
                      mkdocstrings-python \
                      pymdown-extensions \
                      pygments \
                      mkdocs-git-revision-date-localized-plugin
          
      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Build documentation
        run: |
          mkdocs build --strict
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        
      - name: Check documentation links
        run: |
          if [ -f ./site/404.html ]; then
            echo "404 page exists, checking for broken links..."
            if grep -r "404.html" ./site/; then
              echo "Found broken links in the documentation"
              exit 1
            fi
          fi
        
      - name: Deploy to GitHub Pages
        if: github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'docs: update documentation'
          
      - name: Check deployment
        if: github.event_name == 'workflow_dispatch'
        run: |
          sleep 30
          SITE_URL="https://holobiomicslab.github.io/MetaboT/"
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 $SITE_URL)
          if [ $HTTP_STATUS -eq 200 ]; then
            echo "Documentation deployed successfully at $SITE_URL"
          else
            echo "Error: Documentation deployment check failed with status $HTTP_STATUS"
            exit 1
          fi
