name: Evaluate Code

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  evaluate:
    runs-on: ubuntu-22.04
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

   - name: Cache Conda Environment
        uses: actions/cache@v4
        with:
          path: ~/.conda/envs
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

    - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: metabot
          environment-file: environment.yml
          python-version: 3.11.6
          auto-activate-base: false
          auto-update-conda: true

      - name: Cache pip Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Additional Dependencies
        shell: bash -l {0}
        run: |
          conda activate metabot
          pip install -r requirements.txt

      - name: Run Evaluation Script
        shell: bash -l {0}
        run: |
          conda activate metabot
          python -m app.core.evaluation
