name: Evaluate Code

on:
  push:  # Runs on push
  workflow_dispatch:  # Allows manual trigger

jobs:
  evaluate:
    runs-on: ubuntu-latest
    env:
      LANGCHAIN_API_KEY: ${{secrets.LANGCHAIN_API_KEY}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: metabot
        environment-file: environment.yml
        python-version: 3.11
        auto-activate-base: false

    - name: Activate Conda Environment and Run Evaluation Script
      run: |
        source ~/.bashrc  # Ensures Conda is initialized
        conda activate my_env
        python -m app.core.evaluation
