name: Evaluate Code

on: push

jobs:
  evaluate:
    runs-on: ubuntu-latest
    env:
      LANGCHAIN_API_KEY: ${{secrets.LANGCHAIN_API_KEY}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run evaluation script
      run: python -m app.core.evaluation