name: pr_agent.yml

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main
      - dev
      - dev_lfx
      - dev_madina
  workflow_dispatch:
        inputs:
          branch:
            description: "Branch to run action"
            required: false
            default: "dev"
  issue_comment: 
    types: [created]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR-Agent on every pull request and respond to comments
    steps:
      - name: Cache pip dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.txt', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: PR-Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          LITELLM_SET_VERBOSE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          MISTRAL_KEY: ${{ secrets.MISTRAL_KEY }}
          CODESTRAL_KEY: ${{ secrets.CODESTRAL_KEY }}
          CLAUDE_KEY: ${{ secrets.CLAUDE_KEY }}  # Anthropic API key
          HUGGINGFACE_API_KEY : ${{ secrets.HUGGINGFACE_KEY }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGSMITH_PROJECT: ${{ secrets.LANGSMITH_PROJECT }}
          LANGSMITH_BASE_URL: ${{ secrets.LANGSMITH_BASE_URL }}
          
          # Enable Debugging
          DEBUG_MODE: "true"

          # Auto Actions
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
