name: qodo-cover.yml

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened  # Trigger when a pull request is opened

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install system dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11.2"  # Ensure this matches your project's Python version
          auto-update-conda: true

      - name: Create and Activate Conda Environment
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml
          conda activate metabot

      - name: Install Additional Dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt  # If you have additional requirements

      - name: Run Qodo Cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_language: python
          project_root: .
          code_coverage_report_path: ./coverage.xml
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term"
          model: anthropic/claude-3-5-sonnet-latest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_KEY: ${{ secrets.OPENAI_API_KEY }}
          
